baseURL = 'https://omya.games/'
languageCode = 'en-us'
summary = 'summary'
description = 'description'
title = 'Old Man Yells at Games'
theme = 'archie'
[params]
  ReadMore = "Read More"
  [params.Logo]
    logoText = "Old Man Yells at Games"
