baseURL = 'https://omya.games/'
languageCode = 'en-us'
title = 'Old Man Yells at Games'
theme = 'nostyleplease'
[params]
  ReadMore = "Read More"
  [params.Logo]
    logoText = "Old Man Yells at Games"
